config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show] 
  get 'tweets/:tweet_id/likes' => 'likes#create'
  get 'tweets/:tweet_id/likes/:id' => 'likes#destroy'
  get 'tweets/about' => 'about_tweet'
  resources :tweets

  resources :tweets do
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create]
  end
  
  root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true
  has_many :tweet_tag_relations, dependent: :destroy
  has_many :tweets, through: :tweet_tag_relations, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :tweet_tag_relations, dependent: :destroy
  has_many :tags, through: :tweet_tag_relations, dependent: :destroy
  has_many :comments, dependent: :destroy
  
end

app/models/tweet_tag_relation.rb
class TweetTagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

 devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable

has_many :tweets, dependent: :destroy
has_many :likes, dependent: :destroy
has_many :liked_tweets, through: :likes, source: :tweet
validates :name, presence: true 
validates :profile, length: { maximum: 200 }
  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
has_one_attached :image 
has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

 before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
   devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
   devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    tweet = Tweet.find(params[:tweet_id])
    comment = tweet.comments.build(comment_params)
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path) 
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
     def create
    like = current_user.likes.create(tweet_id: params[:tweet_id]) 
    redirect_back(fallback_location: root_path)
  end

  def destroy
    like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

 before_action :authenticate_user!, only: [:new, :create]

def index
    @tweet= Tweet.all
    @tags = Tag.all
    @rank_tweets = Tweet.all.sort {|a,b| b.liked_users.count <=> a.liked_users.count}.take(5)

    @tweet = @tweet.where("kigyoumei LIKE ? ",'%' + params[:search] + '%') if params[:search].present?
    
    if params[:tag_ids].present?
      tweet_ids = []
      params[:tag_ids].each do |key, value| 
        if value == "1"
          Tag.find_by(name: key).tweets.each do |p| 
            tweet_ids << p.id
          end
        end 
      end
    tweet_ids = tweet_ids.uniq
    @tweet = @tweet.where(id: tweet_ids) if tweet_ids.present?
    end
  end

  def new
    @tweet = Tweet.new
  end

  def create
    tweet = Tweet.new(tweet_params)
    
    tweet.user_id = current_user.id

    if tweet.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments
    @comment = Comment.new
    
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

 

    
  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to :action => "show", :id => tweet.id
    else
      redirect_to :action => "new"
    end
  end

  private
  def tweet_params
    params.require(:tweet).permit(:kigyoumei, :start_time, :mypage_url, :image, tag_ids: [])
  end    

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def show
    @user = User.find(params[:id]) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Entry Note" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <script src="https://kit.fontawesome.com/b1501ef68a.js" crossorigin="anonymous"></script>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

 <header>
  <h1>EntryNote</h1>
  <div class="header-list">
   <ul>
    <% if user_signed_in? %>
     <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
     <li><%= link_to "新規登録", new_user_registration_path %></li>
     <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
   </ul>
  </div>
 </header>
 <main>
  <%= yield %>
 </main>

</body>

</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tweets/about.html.erb
<h1>About</h1>
<%= link_to "Tweet一覧に戻る", tweets_path %>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
   <div class = "field" >
  <%= f.label :企業名 %>
  <%= f.text_field :kigyoumei, :size => 140 %> 
  </div>

  <div class = "field" >
    <%= f.label :締切日 %>
    <%= f.datetime_field :start_time, { discard: true} %>
    </div>

  <div class = "field" >
    <%= f.label :マイページURL %>
    <%= f.text_field :mypage_url, :size => 140 %>
  </div>

<div class="field">
    <%= f.label :tags, "あてはまるタグ" %><br>
    <% Tag.all.each do |t| %>
        <label>
        <%= check_box_tag "tweet[tag_ids][]", t.id, @tweet.tags.include?(t) %>
        <%= t.name %>
        </label>
    <% end %>


  <%= f.submit "編集する" %>  
  <%= link_to "一覧に戻る", tweets_path %>
<% end %>

app/views/tweets/index.html.erb
<% if user_signed_in?  %>

 <h3>一覧ページ</h3>
 <%= link_to "About", tweets_about_path %>

  <%= link_to "新規投稿へ", new_tweet_path %>
  <% if user_signed_in? %>
   <%= link_to "マイページへ", user_path(current_user.id) %>
  <% end %>

<h3>投稿を検索</h3>
    <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
       <%= text_field_tag :search %>
          <% Tag.all.each do |t| %>
           <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
          <% end %>
      <%= submit_tag '検索' %>
    <% end %>


  <%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
    <%= text_field_tag :tag %>
    <%= submit_tag 'タグを追加' %>
  <% end %>

   <h3>ランキング</h3>




<% @tweet.each do |t| %>
    <div class="tweet">
        <% if t.image.attached? %>
          <%= image_tag t.image, size: '250x200'%>
        <% end %>
          <%= t.kigyoumei %>
         <%= link_to "詳細", tweet_path(t.id) %>
          <% if user_signed_in? %>
           <% if current_user.already_liked?(t) %>
           <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), data: { turbo_method: :delete } do %>
            <p>いいねを取り消す</p><%= t.likes.count %>
          <% end %>

          <% else %>
            <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), data: { turbo_method: :post }  do %>
           
            <i class="fa-regular fa-thumbs-up"></i>
            <% end %>
          <% end %>

          <% else %>
           <p>いいねの数 = </p><%= t.likes.count %>
           
          <% end %>
       
    </div>
<% end %>




<p id="notice"><%= notice %></p>

<h1>EntryNote</h1>

<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>時間</th>
      <th colspan="3"></th>
    </tr>
      </thead>

      <tbody>
  
     </tbody>
     </table>

  <br>

  <%= link_to '新規投稿へ', new_tweet_path %>

  <%= month_calendar events: @tweet do |date, tweet| %>
   <%= date.day %>

    <% tweet.each do |tweet| %>
      <div>
       <%= link_to tweet.kigyoumei, tweet_path(tweet) %>
       </div>
    <% end %>
 <% end %>


<% end %>

app/views/tweets/new.html.erb
<h3> 新規企業 </h3> 
<%= form_for @tweet do |f| %>
    <div class = "field" >
    <%= f.label :企業名 %>
    <%= f.text_field :kigyoumei, :size => 30 %>
    </div>

    <div class='form-group'>
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class='form-check'>
                <%= tag.label class: 'form-check-label' do %>
                    <%= tag.check_box class: 'form-check-input' %>
                    <%= tag.text %>
                <% end %>
            </div>
        <% end %>
    </div>


    <div class = "field" >
    <%= f.label :締切日 %>
    <%= f.datetime_field :start_time, { discard: true} %>
    </div>



    <div class = "field" >
    <%= f.label :マイページURL %>
    <%= f.text_area :mypage_url, :size => 30 %>
    </div>

    <div class="field">
       <%= f.label :image %>
       <%= f.file_field :image %>
    </div>

    <%= f.submit "投稿する" %>
<% end %>



<%= link_to "一覧に戻る", tweets_path %>



   

app/views/tweets/show.html.erb
<h3>Tweet詳細</h3>
<div class="tweet">
  <p><%= @tweet.kigyoumei %></p>
  <p><%= @tweet.mypage_url %></p>
  <% @tweet.tags.each do |tag| %>
    <span><%= tag.name %></span>
  <% end %>
  <br>

  <p><%= @tweet.created_at %></p>

 <% if user_signed_in? && current_user.id == @tweet.user_id %>
      <%= link_to "編集する", edit_tweet_path(@tweet.id) %>
      <%= link_to "削除する", tweet_path(@tweet.id), method: :delete %>
 <% end %> 


  <% if user_signed_in? %>
     <% if current_user.already_liked?(@tweet) %>
        <%= link_to tweet_like_path(id: @tweet.id, tweet_id: @tweet.id), data: { turbo_method: :delete } do %>
            <p>いいねを取り消す</p><%= @tweet.likes.count %>
     <% end %>
      <% else %>
        <%= link_to tweet_likes_path(id: @tweet.id, tweet_id: @tweet.id), data: { turbo_method: :post }  do %>
            <p>いいね</p><%= @tweet.likes.count %>
        <% end %>
  <% end %>
<% else %>
    <p>いいねの数 = </p><%= @tweet.likes.count %>
<% end %>


<h2>いいねしたユーザー</h2>
<% @tweet.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>
</div>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to "Tweet一覧に戻る", tweets_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>usersshow</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>
<% if @user.image.attached? %>
     <%= image_tag  @user.image, size: '250x200'%>
<% end %>
<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.tweets.each do |t| %>
  <%= t.user.name %>
  <br>
  <%= t.kigyoumei %>
  <br>
  <%= t.start_time %>
  <br>
  <%= t.mypage_url %>
  <% if t.image.attached? %>
          <%= image_tag t.image, size: '250x200'%>
  <% end %>
<% end %>

<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_tweets.each do |t| %>
  <%= t.user.name %>
  <br>
  <%= t.kigyoumei %>
  <br>
  <%= t.start_time %>
  <br>
  <%= t.mypage_url %>
  <br>
  <% if t.image.attached? %>
     <%= image_tag t.image, size: '250x200'%>
     <% end %>
     <%= link_to "詳細へ", tweet_path(t.id) %>
<% end %>
  
<br>
<%= link_to "Tweet一覧に戻る", tweets_path %>